#!/usr/bin/env bash
set -ex
echo -e "2d1\n< set -e" | patch -i - -o src2ndesttol src2ndest
tmpfile=$(mktemp)
sed '/If an error arises src2ndest terminates/,+5 d' src2ndesttol > "$tmpfile"
sed 's/src2ndest/src2ndesttol/g' "$tmpfile" > src2ndesttol
rm "$tmpfile"
