#!/bin/bash

# rsync2multi [OPTION...] SRC [DEST...]
#
# This is a small and simple script to do a rsync from one SRC to multiple DEST.
#
# Every argument starting with "-" is interpreted as an option.
# Every argument not starting with "-" is interpreted as a path.
# The first path is used as SRC and the other paths are used as destinations.
#
#    rsync2multi
#    Copyright (C) 2022  Daniel Mohr
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

if [ $# = "0" ]; then
    /bin/cat <<EOF >&2
rsync2multi [OPTION...] SRC [DEST...]

This is a small and simple bash script to do a rsync from one SRC
to multiple DEST.

The principle is simple:

Every argument starting with "-" is interpreted as an option for rsync.
Every argument not starting with "-" is interpreted as a path.
The first path is used as SRC and the other paths are used as
destinations DEST.

This means you can not give a parameter to a flag directly.
For example, instead of '-B 512' use '--block-size=512' or '"-B 512"'.
Or instead of '-e "ssh -p 2234"' use '--rsh="ssh -p 2234"'.

Example:

rsync2multi -a -r --delete --exclude=.git -v /foo/ /bar/ /baz/

This syncs the directory /foo/ to the two destinations /bar/ and /baz/.
This is similar to:

rsync -a -r --delete --exclude=.git -v /foo/ /bar/
rsync -a -r --delete --exclude=.git -v /foo/ /baz/

Instead of rsync2multi you can also use the much more general tool xargs:

echo /bar/ /baz/ | xargs -n 1 rsync -a -r --delete --exclude=.git -v /foo/

Instead of rsync2multi you can also use the much more general tool parallel
which runs rsync in parallel:

parallel rsync -a -r --delete --exclude=.git -v /foo/ ::: /bar/ /baz/

Example:

rsync2multi -a -r "-e 512" /foo/ /bar/

This syncs the directory /foo/ to the directory /bar/.
This is equivalent to:

rsync -a -r "-e 512" /foo/ /bar/

Author: Daniel Mohr
Date: 2022-11-28
License: GPLv3 or any later version

EOF
    exit 1
fi

declare -a cmdparams=( rsync )
src=""
declare -a dests

for arg in "$@"; do
    if [ "$(echo "$arg" | cut -b1)" = "-" ]; then
	params+=("$arg")
	cmdparams+=("$arg")
    else
	if [ -z "$src" ]; then
	    src="$arg"
	else
	    dests+=("$arg")
	fi
    fi
done

for dest in "${dests[@]}"; do
    "${cmdparams[@]}" "$src" "$dest"
done
